import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/ui/components/ui/card";
import { Input } from "@/ui/components/ui/input";

function ParameterViewer({
  title,
  subtitle,
  paramsJson,
}: {
  title: string;
  subtitle: string;
  paramsJson: string | null;
}) {
  const params = JSON.parse(paramsJson ?? "{}");
  const isEmpty = Object.keys(params).length === 0;

  return (
    <Card>
      <CardHeader className="rounded-lg rounded-b-none border-b py-4 bg-gray-50 dark:bg-background">
        <CardTitle className="text-base">{title}</CardTitle>
        <CardDescription className="text-muted-foreground text-sm">
          {subtitle}
        </CardDescription>
      </CardHeader>

      <CardContent className="py-4">
        <div className="flex flex-col gap-2">
          {isEmpty ? (
            <p className="text-sm">No parameters generated by this phase</p>
          ) : (
            Object.entries(params).map(([key, value]) => (
              <div key={key} className="flex justify-between items-center">
                <p className="text-sm text-muted-foreground flex-1 basis-1/3">
                  {key}
                </p>
                <Input
                  readOnly
                  value={value as string}
                  className="flex-1 basis-2/3"
                />
              </div>
            ))
          )}
        </div>
      </CardContent>
    </Card>
  );
}

export default ParameterViewer;
